# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DATA_PATH": "02_covariables.ipynb",
         "DOWNLOADS_PATH": "02_covariables.ipynb",
         "procesa_registros": "00_etl.ipynb",
         "get_carpetas_from_api": "00_etl.ipynb",
         "get_victimas_from_api": "00_etl.ipynb",
         "get_historico_carpetas": "00_etl.ipynb",
         "get_historico_victimas": "00_etl.ipynb",
         "get_carpetas_desde_archivo": "00_etl.ipynb",
         "get_victimas_desde_archivo": "00_etl.ipynb",
         "agrega_ids_espaciales": "00_etl.ipynb",
         "agregar_categorias_carpetas": "00_etl.ipynb",
         "agregar_categorias_victimas": "00_etl.ipynb",
         "exporta_datos_visualizador": "00_etl.ipynb",
         "serie_de_tiempo_categoria": "00_etl.ipynb",
         "serie_tiempo_categorias_unidades": "00_etl.ipynb",
         "punto_to_hexid": "00_etl.ipynb",
         "agrega_en_hexagonos": "00_etl.ipynb",
         "ajusta_bandwidth_kde": "01_patrones_espacio_temporales.ipynb",
         "kde2D": "01_patrones_espacio_temporales.ipynb",
         "serie_tiempo_kde_categoria": "01_patrones_espacio_temporales.ipynb",
         "serie_razones_de_eventos": "01_patrones_espacio_temporales.ipynb",
         "serie_mapas_intensidad": "01_patrones_espacio_temporales.ipynb",
         "p_value_maps": "01_patrones_espacio_temporales.ipynb",
         "descarga_datos_covariables": "02_covariables.ipynb",
         "get_diccionario_censo": "02_covariables.ipynb",
         "get_variables_censo": "02_covariables.ipynb",
         "imputa_faltantes_manzana": "02_covariables.ipynb",
         "agrega_en_unidades": "02_covariables.ipynb",
         "censo_a_tasas": "02_covariables.ipynb",
         "get_uso_de_suelo": "02_covariables.ipynb",
         "agrega_uso_suelo": "02_covariables.ipynb",
         "IndicePCA": "02_covariables.ipynb",
         "variable_dependiente": "03_modelos.ipynb",
         "CapaDeAnalisis": "03_modelos.ipynb",
         "ModeloGLM": "03_modelos.ipynb",
         "ComparaModelos": "03_modelos.ipynb"}

modules = ["etl.py",
           "patrones_espacio_temporales.py",
           "covariables.py",
           "modelos.py"]

doc_url = "https://pages.github.CentroGeo.com./criminologia_cdmx/criminologia_cdmx/"

git_url = "https://github.CentroGeo.com/criminologia_cdmx/criminologia_cdmx/tree/master/"

def custom_doc_links(name): return None
