# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_carpetas_from_api": "00_etl.ipynb",
         "get_historico_carpetas": "00_etl.ipynb",
         "agrega_ids_espaciales": "00_etl.ipynb",
         "agregar_categorias_de_usuario": "00_etl.ipynb",
         "exporta_datos_vusualizador": "00_etl.ipynb",
         "ajusta_bandwidth_kde": "01_patrones_espacio_temporales.ipynb",
         "kde2D": "01_patrones_espacio_temporales.ipynb",
         "serie_tiempo_kde_categoria": "01_patrones_espacio_temporales.ipynb"}

modules = ["etl.py",
           "patrones_espacio_temporales.py"]

doc_url = "https://plablo09.github.io/criminologia_cdmx/"

git_url = "https://github.com/plablo09/criminologia_cdmx/tree/master/"

def custom_doc_links(name): return None
